events/urls.py
from django.conf.urls.defaults import patterns, url

from views import *

urlpatterns = patterns('',
    url(r'^$', home, {}, 'home'),
    url(r'^(?P<event_id>[0-9]+)/$', event, {}, 'event'),
    url(r'^url/(?P<secret_url>\w+)/$', event, {}, 'event-secret'),
    url(r'^cart/$', cart, {}, 'cart'),
    url(r'^cart/clear/$', cart, {'clear' : True}, 'cart-clear'),
    url(r'^cart/checkout/$', cart_checkout, {}, 'cart-checkout'),
    url(r'^search/$', search, {}, 'search'),
    url(r'^create/$', create_event, {}, 'create-event'),
    url(r'^create/ticket/$', create_ticket, {}, 'create-ticket'),
    # AUTH
    url(r'^login/$', login_user, {}, 'login'),
    url(r'^signup/$', register_user, {}, 'register'),
    url(r'^logout/$', logout_user, {}, 'logout'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.shortcuts import redirect

admin.autodiscover()

# simple redirection to events - remove it (and the first url pattern)
# if you want to have a different view under the base URL.
def redirect_to_events(request):
    return redirect('home')

urlpatterns = patterns('',
    url(r'^$', redirect_to_events, {}, 'redirect-to-events'),                   
    url(r'^events/', include('events.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'events.views.login_user', {}, 'login-redirect'),
)

urlpatterns += staticfiles_urlpatterns()

events/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils.hashcompat import sha_constructor
from django.utils.translation import ugettext_lazy as _

class Event(models.Model):
    created_by = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    logo = models.ImageField(upload_to='event_logos', null=True, blank=True,
                             verbose_name=_('Event logo'))
    name = models.CharField(max_length=256, verbose_name=_('Event name'))
    date_start = models.DateTimeField(verbose_name=_('Event start'))
    date_end = models.DateTimeField(verbose_name=_('Event end'))
    # preferrably changed to geo-location later
    location = models.CharField(max_length=128, verbose_name=_('Event location')) 
    description = models.TextField(verbose_name=_('Event details'))
    private = models.BooleanField(default=False, verbose_name=_('Event is private'))
    secret_url = models.CharField(max_length=40, null=True, blank=True)
    
    class Meta:
        verbose_name = _('Event')
        verbose_name_plural = _('Events')
        ordering = ('date_start',)
        
    def __unicode__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if self.private:
            key = self.created_by.email+str(self.created_at)+self.name
            self.secret_url = sha_constructor(key).hexdigest()
        super(Event, self).save(*args, **kwargs)
    
class Ticket(models.Model):
    event = models.ForeignKey(Event)
    name = models.CharField(max_length=64)
    # if quantity is null, the number of available tickets is unlimited
    quantity = models.PositiveIntegerField(null=True, blank=True)
    # number of tickets that can be bought at once, null = unlimited
    quantity_limit = models.PositiveIntegerField(null=True, blank=True)
    price = models.FloatField()
    sales_start = models.DateTimeField(null=True, blank=True)
    sales_end = models.DateTimeField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    
    class Meta:
        verbose_name = _('Ticket')
        verbose_name_plural = _('Tickets')
        
    def __unicode__(self):
        return _(u'Ticket for ') + unicode(self.event.name)
        
    def quantity_range(self):
        if self.quantity_limit:
            return range(0,self.quantity_limit+1,1)
        else:
            return range(0,self.quantity+1,1)
            
    def tickets_left(self):
        if not self.quantity:
            return -1
        else:
            quantity = 0
            # TODO Change to aggregate
            checked_orders = TicketOrder.objects.filter(ticket=self, cart__checked_out=True)
            for order in checked_orders:
                quantity += order.quantity
            return self.quantity - quantity
            
    def sold_out(self):
        if self.quantity:
            quantity = 0
            # TODO Change to aggregate
            checked_orders = TicketOrder.filter(ticket=self, cart__checked_out=True)
            for order in checked_orders:
                quantity += order.quantity
            if quantity >= self.quantity:
                return True
        return False
            
    def sales_started(self):
        if self.sales_start:
            return self.sales_start > datetime.datetime.now()
        else:
            return True
            
    def sales_finished(self):
        if self.sales_end:
            return self.sales_end < datetime.datetime.now()
        else:
            return self.event.date_end < datetime.datetime.now()
    
class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True,
                                         verbose_name=_('Creation date'))
    checked_out = models.BooleanField(default=False,
                                      verbose_name=_('Checked out'))

    class Meta:
        verbose_name = _('Cart')
        verbose_name_plural = _('Carts')
        ordering = ('-creation_date',)

    def __unicode__(self):
        return unicode(self.creation_date)
    
class TicketOrder(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=_('Cart'))
    quantity = models.PositiveIntegerField(verbose_name=_('Quantity'))
    ticket = models.ForeignKey(Ticket, verbose_name = _('Ticket'))

    class Meta:
        verbose_name = _('Ticket Order')
        verbose_name_plural = _('Ticket Orders')
        ordering = ('cart',)

    def __unicode__(self):
        return u'%d tickets (%s) for %s' % (self.quantity, self.ticket.name,
                                            self.ticket.event.name)
        
    def total_price(self):
        return self.quantity * self.ticket.price
    total_price = property(total_price)

events/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

from models import Event, Ticket

class LoginForm(forms.Form):
    email = forms.EmailField(label=_('E-mail'))
    password = forms.CharField(max_length=30, widget=forms.PasswordInput,
                               label=_('Password'))
    
class RegisterForm(forms.Form):
    email = forms.EmailField(label=_('E-mail'))
    password = forms.CharField(max_length=30, widget=forms.PasswordInput,
                               label=_('Password'))
    re_password = forms.CharField(max_length=30, widget=forms.PasswordInput,
                               label=_('Retype password'))
    
    def clean(self):
        cd = self.cleaned_data
        email = cd.get('email')
        if User.objects.filter(email=email):
            raise forms.ValidationError(_('User with given e-mail already exists'))
        passwd1 = cd.get('password')
        passwd2 = cd.get('re_password')
        if passwd1 != passwd2:
            raise forms.ValidationError(_('Passwords did not match'))
        return cd
    
class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude = ('created_by', 'secret_url')
        
class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        exclude = ('event',)
        

events/views.py
import stripe

from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _

from cart import Cart as CartManager
from models import *
from forms import *

def home(request, template='events/home.html'):
    events = Event.objects.filter(private=False)
    paginator = Paginator(events, 5)
    page = request.REQUEST.get('page')
    if page:
        page = int(page)
    try:
        events = paginator.page(page)
    except:
        events = paginator.page(1)
    context = {
        'events' : events
    }
    return render_to_response(template, context,
                              context_instance=RequestContext(request))
    
def event(request, event_id=None, secret_url=None, template='events/event.html'):
    if event_id:
        event = get_object_or_404(Event, pk=event_id)
    else:
        event = get_object_or_404(Event, secret_url=secret_url)
    if request.method == 'POST':
        ticket_quantity = request.POST.get('ticket_quantity')
        if ticket_quantity:
            ticket_quantity = ticket_quantity.split(',')
            cart = CartManager(request)
            for t_q in ticket_quantity:
                t_q = t_q.split(':')
                ticket = Ticket.objects.get(pk=t_q[0])
                quantity = t_q[1]
                cart.add(ticket, quantity)
            return redirect('cart')
    context = {
        'event' : event
    }
    return render_to_response(template, context,
                              context_instance=RequestContext(request))

@login_required    
def cart(request, clear=False, template='events/cart.html'):
    cart = CartManager(request)
    if clear:
        cart.clear()
        return redirect('home')
    context = {
        'cart' : cart,
        'STRIPE_PUBLIC_KEY' : settings.STRIPE_PUBLIC_KEY
    }
    return render_to_response(template, context,
                              context_instance=RequestContext(request))

@login_required    
def cart_checkout(request, template='events/cart_checkout.html'):
    context = {}
    cart = CartManager(request)
    if request.method == 'POST':
        try:
            stripe.api_key = settings.STRIPE_PRIVATE_KEY
            # get the credit card details submitted by the form
            token = request.POST['stripeToken']
            # create the charge on Stripe's servers - this will charge the user's card
            charge = stripe.Charge.create(
                amount=int(cart.summary()*100), # amount in cents
                currency="usd",
                card=token,
                description=request.user.email
            )
            if charge.get('paid'):
                subject = _(u'[Django Events] Your purchase has been accepted.')
                message = 'You bought:\n'
                for ticket_order in cart:
                    message += '%s * %s for %s\n' % (ticket_order.quantity,
                                                     ticket_order.ticket.name,
                                                     ticket_order.ticket.event.name)
                send_mail(subject, message, 'noreply@django-events.com',
                          [request.user.email], fail_silently=True)
                cart.check_out()
                return HttpResponse('TRUE')
            return HttpResponse('FALSE')
        except:
            import traceback
            traceback.print_exc()
    
def search(request, template='events/home.html'):
    query = request.GET.get('search')
    events = Event.objects.all()
    if query:
        events = events.filter(name__icontains=query)
    paginator = Paginator(events, 5)
    page = request.REQUEST.get('page')
    if page:
        page = int(page)
    try:
        events = paginator.page(page)
    except:
        events = paginator.page(1)
    context = {
        'events' : events,
        'query' : query
    }
    return render_to_response(template, context,
                              context_instance=RequestContext(request))
    
@login_required
def create_event(request, template='events/event_create.html'):
    event = None
    ticket_forms = []
    ticket_prefixes = []
    ticket_number = 0
    if request.method == 'POST':
        tickets_valid = True
        ticket_prefixes = request.POST.get('ticket_prefixes')
        if ticket_prefixes:
            ticket_prefixes = ticket_prefixes.split(',')
            # get the ticket prefix of the possible next ticket form
            ticket_number = int(ticket_prefixes[-1]) + 1
            for ticket_prefix in ticket_prefixes:
                ticket_form = TicketForm(request.POST, prefix=ticket_prefix)
                if not ticket_form.is_valid():
                    tickets_valid = False
                ticket_forms.append(ticket_form)
        event_form = EventForm(request.POST, prefix='event')
        if event_form.is_valid() and tickets_valid:
            event = event_form.save(commit=False)
            event.created_by = request.user
            event.save()
            for ticket_prefix in ticket_prefixes:
                ticket_form = TicketForm(request.POST, prefix=ticket_prefix)
                ticket = ticket_form.save(commit=False)
                ticket.event = event
                ticket.save()
        else:
            print 'THERE ARE SOME ERRORS!'
            print event_form.errors
            for form in ticket_forms:
                print form.errors
    else:
        event_form = EventForm(prefix='event')
    context = {
        'event_form' : event_form,
        'ticket_forms' : ticket_forms,
        'ticket_number' : ticket_number,
        'ticket_prefixes' : ticket_prefixes,
        'event' : event
    }
    return render_to_response(template, context,
                              context_instance=RequestContext(request))

@login_required
def create_ticket(request, template='events/event_create_ticket.html'):
    ticket_number = request.GET.get('ticket_number')
    #print 'TICKET NO: ', ticket_number
    ticket_form = TicketForm(prefix=ticket_number)
    context = {
        'ticket_form' : ticket_form,
        'ticket_number' : ticket_number
    }
    return render_to_response(template, context,
                              context_instance=RequestContext(request))

#------------------------------------ AUTH ------------------------------------
    
def login_user(request, template='events/login.html'):
    incorrect_data = False
    if request.method == 'POST':
        incorrect_data = True
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['email']
            password = form.cleaned_data['password']
            # check if user signed in using e-mail
            try:
                user = User.objects.get(email=username)
                user = authenticate(username=user.username, password=password)
                if user is not None:
                    if user.is_active:
                        login(request,user)
                        if request.GET.has_key('next'):
                            return redirect(request.GET['next'])
                        return redirect('home')
            except User.DoesNotExist:
                pass
    else:
        form = LoginForm()
    context = {
        'form' : form,
        'incorrect_data' : incorrect_data
    }
    return render_to_response(template, context,
                              context_instance=RequestContext(request))
    
def register_user(request, template='events/register.html'):
    user_exists = False
    saved = False
    if request.POST:
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            # create username from email substring
            username = email[0:email.index('@')]
            if User.objects.filter(username=username):
                # append a number to the username until a non-existing found
                count = 0
                while User.objects.filter(username=username):
                    count += 1
                    username = username + str(count)
            else:
                user = User()
                user.email = email
                user.set_password(password)
                user.username = username
                user.save()
                user = authenticate(username=user.username, password=password)
                login(request, user)
                saved = True
    else:
        form = RegisterForm()
    context = {
        'form' : form,
        'user_exists' : user_exists,
        'saved' : saved,
    }
    return render_to_response(template, context,
                              context_instance=RequestContext(request))

def logout_user(request):
    logout(request)
    if request.GET.get('next'):
        return HttpResponseRedirect(request.GET['next'])
    else:
        return redirect('home')
        

events/templates/events/base.html
{%load i18n events_tags%}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-Language" content="en"/>
    <link rel="shortcut icon" href="{{STATIC_URL}}images/favicon.ico"/>
    <meta name="keywords" content="events, online registration, sell tickets, event management, credit cards, online payments"/>
    <meta name="robots" content="index, follow"/>
    <meta name="description" content="Django Events gives you all the online tools you need to bring people together for an event and sell tickets."/>
    <link rel="image_src" href="#"/>
    <title>Django Events - {%trans "Sell Tickets Online"%}</title>
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/base.css"/>
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/fonts.css"/>
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/home.css"/>
    <script type="text/javascript" src="{{STATIC_URL}}js/jquery-1.7.2.min.js"></script>
    {%block extra_header%}{%endblock%}
</head>
<body>
<div id="header">
    <div id="header_content">
        <a id="logo" href="{%url home%}">
            <h1>Logo</h1>
        </a>
        <div id="ticket_counter">
            <span class="strong">
                {%count_sold_tickets%}
            </span>
            <span>{%trans "Tickets sold"%}</span>
        </div>

        <div id="lang-auth">
            LANGUAGE FLAGS PLACEHOLDER
            {%if request.user.is_authenticated%}
                <span style="margin-left:10px;">
                    {%trans "Signed in as"%}:
                    {{request.user.email}}
                </span>
                <a href="{%url logout%}">{%trans "Log out"%}</a>
            {%else%}
                <a href="{%url login%}">{%trans "Log in"%}</a>
                <a href="{%url register%}">{%trans "Sign up"%}</a>
            {%endif%}
        </div>
        
        <ul id="header_nav">
            <li style="margin-bottom:7px;">
                <a href="{%url create-event%}">{%trans "Create an event"%}</a>
            </li>
        </ul>
    </div>
</div>

<div id="home_container">
    {%block top_slider%}{%endblock%}

    <section id="event_discovery" class="clrfix">
        {%block content%}{%endblock%}
    </section>
</div>

<div id="footer">    
    <div id="fine_print">
        FOOTER
    </div>
</div>

</body>
</html>

events/templates/events/cart.html
{%extends 'events/base.html'%}
{%load i18n%}

{%block content%}
    <div class="event-detail" style="width:599px;min-height:220px;float:left;border-right:1px dotted #ccc;">
        <h1>{%trans "CART"%}</h1>
        <h2 style="margin-top:20px;">{%trans "Order summary"%}</h2>
        <table class="tickets" style="width:100%;">
            <thead>
                <tr>
                    <th>{%trans "TICKET TYPE"%}</th>
                    <th>{%trans "PRICE"%}</th>
                    <th>{%trans "QUANTITY"%}</th>
                    <th>{%trans "TOTAL"%}</th>
                </tr>
            </thead>
            <tbody>
                {%for ticket_order in cart%}
                    <tr>
                        <td>
                            {{ticket_order.ticket.name}}
                            <p class="description">{{ticket_order.ticket.description}}</p>
                        </td>
                        <td>{{ticket_order.ticket.price|floatformat:2}}</td>
                        <td>{{ticket_order.quantity}}</td>
                        <td>{{ticket_order.total_price|floatformat:2}}</td>
                    </tr>
                {%endfor%}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" style="text-align:right;">
                        {%trans "TOTAL AMOUNT DUE"%}:
                    </td>
                    <td><strong>{{cart.summary|floatformat:2}}</strong></td>
                </tr>
            </tfoot>
        </table>
        <a href="{%url cart-clear%}" id="clear" class="action_button action_button_go" style="margin:10px 5px;">
            {%trans "Clear cart"%}
        </a>
    </div>
    <div class="checkout-form">
        {%include 'events/cart_checkout_ajax.html'%}
    </div>
    <div class="ajax-loader">{%trans "Your payment is being processed"%}</div>
    <div class="ajax-success">
        {%trans "Your payment has been accepted. Thank you!"%}<br/><br/>
        <a href="{%url home%}">{%trans "Go back home"%}</a>
    </div>
    <div class="ajax-failure">
        {%trans "Sorry, your payment could not be processed."%}<br/><br/>
        {%trans "Please try again later."%}
    </div>
{%endblock%}

events/templates/events/event.html
{%extends 'events/base.html'%}
{%load i18n events_tags%}

{%block content%}
    <div class="event-detail">
        <h1>{{event}}</h1>
        <p class="info">
            {{event.date_start|date:'l, F j, Y'}} at {{event.date_start|date:'g:i A'}}
            -
            {{event.date_end|date:'l, F j, Y'}} at {{event.date_end|date:'g:i A'}}
        </p>
        <p class="info">{{event.location}}</p>
        {%if event.ticket_set.all.count%}
            <h2 style="margin-top:20px;">{%trans "Available tickets"%}</h2>
            <table class="tickets">
                <thead>
                    <tr>
                        <th>{%trans "TICKET TYPE"%}</th>
                        <th>{%trans "SALES START"%}</th>
                        <th>{%trans "SALES END"%}</th>
                        <th>{%trans "PRICE"%}</th>
                        <th>{%trans "QUANTITY"%}</th>
                    </tr>
                </thead>
                <tbody>
                    {%for ticket in event.ticket_set.all%}
                        <tr>
                            <td>
                                {{ticket.name}}
                                {%with tickets_left=ticket.tickets_left%}
                                    {%if tickets_left > 0 and tickets_left < 10%}
                                    <span class="few-left">
                                        {{ticket.tickets_left}} {%trans "left"%}
                                    </span>
                                    {%endif%}
                                {%endwith%}
                                <p class="description">{{ticket.description}}</p>
                            </td>
                            <td>
                                {%if ticket.sales_started%}
                                    {%trans "Started"%}
                                {%else%}
                                    {{ticket.sales_start|time_left}}
                                {%endif%}
                            </td>
                            <td>
                                {%if ticket.sales_finished%}
                                    {%trans "Finished"%}
                                {%else%}
                                    {%if ticket.sales_end%}
                                        {{ticket.sales_end|time_left}}
                                    {%else%}
                                        {{event.date_end|time_left}}
                                    {%endif%}
                                {%endif%}
                            </td>
                            <td>{{ticket.price|floatformat:2}}</td>
                            <td>
                                {%if not ticket.sales_finished%}
                                    <select class="ticket-select" id="{{ticket.id}}" name="ticket-{{ticket.id}}">
                                        {%for opt in ticket.quantity_range%}
                                            <option>{{opt}}</option>
                                        {%endfor%}
                                    </select>
                                {%else%}
                                    --------------
                                {%endif%}
                            </td>
                        </tr>
                    {%endfor%}
                </tbody>
            </table>
            <form id="buy-tickets-form" action="#" method="POST">
                {%csrf_token%}
                <input type="hidden" name="ticket_quantity" id="id_ticket_quantity"/>
            </form>
            <a href="#" class="action_button action_button_go" style="margin:10px 0;">
                {%trans "Get Tickets"%}
            </a>
        {%endif%}
        <h2 style="margin:20px 0 10px;">{%trans "Event details"%}</h2>
        <div>{{event.description|linebreaksbr}}</div>
    </div>
    <script type="text/javascript">
        $(function() {
            $('.action_button').click(function() {
                var ticket_quantity = new Array();
                $('.ticket-select').each(function() {
                    if($(this).val() != '0') {
                        ticket_quantity.push($(this).attr('id')+':'+$(this).val());
                    }
                });
                $('#id_ticket_quantity').val(ticket_quantity.toString());
                $('#buy-tickets-form').submit();
            });
        });
    </script>
{%endblock%}

events/templates/events/event_create.html
{%extends 'events/base.html'%}
{%load i18n%}

{%block content%}
    {%if event%}
        {%trans "The event has been successfully created."%}
        {%if event.private%}
            {%trans "Your events is private. Its secret link is"%}:<br/>
            <a href="{%url event-secret event.secret_url%}">
                {{request.get_host}}{%url event-secret event.secret_url%}
            </a>
        {%endif%}<br/>
        <a href="{%url home%}">{%trans "Get back to the homepage"%}</a>
    {%else%}
        <form id="event" action="{%url create-event%}" method="POST">
            {%csrf_token%}
            <div class="event-form">
                <h2>{%trans "Event details"%}</h2>
                {%for field in event_form%}
                    <div style="margin-top:10px;">
                        <div class="label">
                            {{field.label_tag}}
                            {%if field.field.required%}
                                <span class="required">*</span>
                            {%endif%}
                        </div>
                        {{field}}
                        {%if field.errors%} <br/>{{field.errors}} {%endif%}
                    </div>
                {%endfor%}
                {%if form.non_field_errors%}
                    <div class="error">
                        {{form.non_field_errors}}
                    </div>
                {%endif%}
                <div style="text-align:center">
                    <input type="submit" value="{%trans "Create"%}"/>
                </div>
            </div>
        
            <div class="event-form ticket">
                <input type="hidden" name="ticket_number" id="id_ticket_number" value="{{ticket_number}}"/>
                <input type="hidden" name="ticket_prefixes" id="id_ticket_prefixes" value=""/>
                <h2>{%trans "Ticket details"%}</h2>
                <div id="id_ticket_placeholder">
                    {%for ticket_form in ticket_forms%}
                        {%include 'events/event_create_ticket.html'%}
                    {%endfor%}
                </div>
                <div style="text-align:center">
                    <input type="button" id="add-ticket" value="{%trans "Add ticket"%}"/>
                </div>
            </div>
        </form>
        <script type="text/javascript">
            $(function() {
                var ticket_number = $('#id_ticket_number');
                {%if ticket_prefixes%}
                    var ticket_prefixes = new Array(
                        {%for prefix in ticket_prefixes%}
                            '{{prefix}}'{%if not forloop.last%},{%endif%}
                        {%endfor%}
                    );
                {%else%}
                    var ticket_prefixes = new Array();
                {%endif%}
                var ticket_placeholder = $('#id_ticket_placeholder');
                $('#add-ticket').click(function() {
                    $.ajax({
                        url : '{%url create-ticket%}',
                        data : {
                            ticket_number : ticket_number.val()
                        },
                        success : function(response) {
                            ticket_placeholder.append($(response));
                            ticket_prefixes.push(ticket_number.val());
                            ticket_number.val(parseInt(ticket_number.val())+1);
                        },
                        error : function() {
                            alert('{%trans "An error occurred."%}');
                        }
                    })
                });
                
                $('.delete-tick').live('click', function() {
                    ticket_prefixes.splice(
                        ticket_prefixes.indexOf($(this).attr('id')),
                        1
                    );
                    $(this).parent().remove();
                    //alert(ticket_prefixes);
                });
                
                $('#event').submit(function() {
                    $('#id_ticket_prefixes').val(ticket_prefixes.toString());
                });
            });
        </script>
    {%endif%}
{%endblock%}

events/templates/events/login.html
{%extends 'events/base.html'%}
{%load i18n%}

{%block content%}
    <div class="auth-form" style="padding:30px;">
        <form action="#" method="POST">
            {%csrf_token%}
            {%for field in form%}
                <div style="margin-top:10px;">
                    {{field.label_tag}} {{field}}
                    {%if field.errors%} <br/>{{field.errors}} {%endif%}
                </div>
            {%endfor%}
            {%if incorrect_data%}
                <div class="error">
                    {%trans "User with given e-mail/password does not exist."%}
                </div>
            {%endif%}
            <input type="submit" value="{%trans "Log in"%}"/>
        </form>
    </div>
{%endblock%}